const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const audio=$("#audio"),libraryEl=$("#library"),emptyState=$("#emptyState"),progress=$("#progress");
let tracks=[],catalog=[],jamendo=[],currentIndex=-1,currentView="all",mainView="library",query="",demoCtx=null,demoTimer=null,demoPlaying=false,searchTimer=null;
const DB="musicTK",STORE="tracks",DOWNLOADED_KEY="musicTK-downloaded-sources",JAMENDO_CLIENT_ID="709fa152";
const downloadedSources=new Set(JSON.parse(localStorage.getItem(DOWNLOADED_KEY)||"[]"));
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getTracks(){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction(STORE,"readonly").objectStore(STORE).getAll();t.onsuccess=()=>resolve(t.result);t.onerror=()=>reject(t.error)})}
async function putTrack(x){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction(STORE,"readwrite").objectStore(STORE).put(x);t.onsuccess=resolve;t.onerror=()=>reject(t.error)})}
async function removeTrack(id){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction(STORE,"readwrite").objectStore(STORE).delete(id);t.onsuccess=resolve;t.onerror=()=>reject(t.error)})}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function fmt(s){if(!Number.isFinite(s))return"0:00";return Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0")}
function render(){const list=tracks.filter(t=>(currentView==="favorites"?t.favorite:true)&&(!query||t.name.toLowerCase().includes(query)||t.artist.toLowerCase().includes(query)));libraryEl.innerHTML=list.map(t=>`<article class="track"><div class="cover">♫</div><div class="track-info"><strong>${esc(t.name)}</strong><small>${esc(t.artist)} · ${esc(t.type||"Audio")}</small></div><div class="track-actions"><button class="small-btn favorite" data-fav="${t.id}" aria-label="Favorite">${t.favorite?"♥":"♡"}</button><button class="small-btn" data-play="${t.id}" aria-label="Play">▶</button><button class="small-btn" data-delete="${t.id}" aria-label="Delete">×</button></div></article>`).join("");emptyState.style.display=list.length?"none":"block"}
async function refresh(){tracks=await getTracks();render()}
function renderDiscover(){const q=query.trim();const list=jamendo.filter(t=>!downloadedSources.has(t.id)&&(!q||t.title.toLowerCase().includes(q)||t.artist.toLowerCase().includes(q)));$("#discoverCount").textContent=list.length;$("#discoverList").innerHTML=list.map(t=>`<article class="track discover-track"><div class="cover">♫</div><div class="track-info"><strong>${esc(t.title)}</strong><small>${esc(t.artist)} · ${esc(t.license||"Jamendo")}</small></div><div class="track-actions"><button class="small-btn" data-stream="${esc(t.id)}" aria-label="Preview">▶</button>${t.downloadAllowed?`<button class="small-btn download-btn" data-download="${esc(t.id)}" aria-label="Download">⇩</button>`:""}</div></article>`).join("");$("#discoverStatus").textContent=list.length?`${list.length} Jamendo tracks found. Tracks marked downloadable can be saved offline.` : (q?"No Jamendo tracks found. Try another search.":"Search for music to begin.")}
async function searchJamendo(term){const status=$("#discoverStatus");if(!term){jamendo=[];renderDiscover();return}status.textContent="Searching Jamendo…";try{const params=new URLSearchParams({client_id:JAMENDO_CLIENT_ID,format:"json",limit:"30",search:term,audioformat:"mp32",audiodlformat:"mp32",include:"musicinfo"});const r=await fetch("https://api.jamendo.com/v3.0/tracks/?"+params);if(!r.ok)throw Error("Jamendo API error");const data=await r.json();jamendo=(data.results||[]).map(t=>({id:"jamendo:"+t.id,title:t.name,artist:t.artist_name||"Unknown artist",duration:Number(t.duration)||0,audio:t.audio,audiodownload:t.audiodownload,downloadAllowed:t.audiodownload_allowed===true,license:t.license_ccurl||"Jamendo",image:t.image||t.album_image}));renderDiscover()}catch(e){jamendo=[];$("#discoverList").innerHTML="";status.textContent="Jamendo search could not be reached. Check the connection and try again."}}
async function downloadJamendo(id,button){const t=jamendo.find(x=>x.id===id);if(!t||!t.downloadAllowed||!t.audiodownload)return;button.disabled=true;button.textContent="…";try{const r=await fetch(t.audiodownload);if(!r.ok)throw Error("Download failed");const blob=await r.blob();await putTrack({id:crypto.randomUUID(),name:t.title,artist:t.artist,type:blob.type||"audio/mpeg",favorite:false,blob,sourceId:t.id,source:"Jamendo",license:t.license});downloadedSources.add(t.id);localStorage.setItem(DOWNLOADED_KEY,JSON.stringify([...downloadedSources]));await refresh();renderDiscover()}catch(e){button.disabled=false;button.textContent="⇩";alert("This Jamendo track could not be saved. Try another downloadable track.")}}
function playJamendo(t){stopDemo();audio.src=t.audio;audio.play();currentIndex=-1;$("#playerTitle").textContent=t.title;$("#playerArtist").textContent=t.artist;$("#playBtn").textContent="❚❚"}
function stopDemo(){if(demoTimer)clearInterval(demoTimer);demoTimer=null;demoPlaying=false;if(demoCtx){demoCtx.close();demoCtx=null}}
function startDemo(name){audio.pause();stopDemo();demoPlaying=true;$("#playBtn").textContent="❚❚";const titles={morning:"Morning Drive",midnight:"Midnight City",sunrise:"Sunrise"};$("#playerTitle").textContent=titles[name];$("#playerArtist").textContent="musicTK Demo";let i=0;const notes={morning:[261.63,329.63,392,523.25],midnight:[220,277.18,329.63,440],sunrise:[293.66,349.23,440,587.33]}[name];demoCtx=new(window.AudioContext||window.webkitAudioContext)();const playNote=()=>{const o=demoCtx.createOscillator(),g=demoCtx.createGain();o.frequency.value=notes[i++%notes.length];o.type="sine";g.gain.setValueAtTime(.0001,demoCtx.currentTime);g.gain.exponentialRampToValueAtTime(.12,demoCtx.currentTime+.03);g.gain.exponentialRampToValueAtTime(.0001,demoCtx.currentTime+.42);o.connect(g).connect(demoCtx.destination);o.start();o.stop(demoCtx.currentTime+.45)};playNote();demoTimer=setInterval(playNote,480)}
function playTrack(t){stopDemo();const url=URL.createObjectURL(t.blob);audio.src=url;audio.play();currentIndex=tracks.findIndex(x=>x.id===t.id);$("#playerTitle").textContent=t.name;$("#playerArtist").textContent=t.artist;$("#playBtn").textContent="❚❚"}
$("#importBtn").onclick=()=>$("#fileInput").click();$("#emptyImportBtn").onclick=()=>$("#fileInput").click();
$("#fileInput").onchange=async e=>{for(const f of e.target.files){await putTrack({id:crypto.randomUUID(),name:f.name.replace(/\.[^.]+$/,""),artist:"Imported",type:f.type||"Audio",favorite:false,blob:f})}e.target.value="";await refresh()};
$$('.main-tabs .tab').forEach(b=>b.onclick=()=>{$$('.main-tabs .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');mainView=b.dataset.mainView;$("#libraryView").hidden=mainView!=="library";$("#discoverView").hidden=mainView!=="discover";$("#searchInput").placeholder=mainView==="discover"?"Search Jamendo music...":"Search your library...";mainView==="discover"?renderDiscover():render()});
$$('.sub-tabs .tab').forEach(b=>b.onclick=()=>{$$('.sub-tabs .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentView=b.dataset.view;render()});
$("#searchInput").oninput=e=>{query=e.target.value.trim().toLowerCase();if(mainView!=="discover"){render();return}clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchJamendo(query),350)};
libraryEl.onclick=async e=>{const p=e.target.closest("[data-play]"),d=e.target.closest("[data-delete]"),f=e.target.closest("[data-fav]");if(p){const t=tracks.find(x=>x.id===p.dataset.play);if(t)playTrack(t)}if(d){await removeTrack(d.dataset.delete);await refresh()}if(f){const t=tracks.find(x=>x.id===f.dataset.fav);if(t){t.favorite=!t.favorite;await putTrack(t);render()}}};
$("#discoverList").onclick=e=>{const d=e.target.closest("[data-download]"),p=e.target.closest("[data-stream]");if(d)downloadJamendo(d.dataset.download,d);if(p){const t=jamendo.find(x=>x.id===p.dataset.stream);if(t)playJamendo(t)}};
$$('.demo-card').forEach(b=>b.onclick=()=>startDemo(b.dataset.demo));
$("#playBtn").onclick=()=>{if(demoPlaying){stopDemo();$("#playBtn").textContent="▶";return}if(audio.src){audio.paused?audio.play():audio.pause()}else if(tracks[0])playTrack(tracks[0])};
$("#prevBtn").onclick=()=>{if(!tracks.length)return;playTrack(tracks[(currentIndex-1+tracks.length)%tracks.length])};$("#nextBtn").onclick=()=>{if(!tracks.length)return;playTrack(tracks[(currentIndex+1)%tracks.length])};
audio.onplay=()=>$("#playBtn").textContent="❚❚";audio.onpause=()=>$("#playBtn").textContent="▶";audio.ontimeupdate=()=>{progress.value=audio.duration?(audio.currentTime/audio.duration)*100:0;$("#currentTime").textContent=fmt(audio.currentTime)};audio.onloadedmetadata=()=>$("#duration").textContent=fmt(audio.duration);progress.oninput=()=>{if(audio.duration)audio.currentTime=(progress.value/100)*audio.duration};audio.onended=()=>$("#nextBtn").click();
if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});refresh();loadCatalog();